{% set version = "33.5" %}
{% set major_version = "6" %}

package:
  name: protobuf-bazel-rules
  version: {{ version }}

source:
  - url: https://github.com/protocolbuffers/protobuf/releases/download/v{{ version }}/protobuf-{{ version }}.tar.gz
    sha256: c6c7c27fadc19d40ab2eaa23ff35debfe01f6494a8345559b9bb285ce4144dd1

build:
  number: 0

requirements:
  run_constrained:
    - protobuf {{ major_version }}.{{ version }}.*
    - libprotobuf {{ major_version }}.{{ version }}.*

test:
  commands:
    - test -f ${PREFIX}/share/bazel/protobuf/bazel/cc_proto_library.bzl  # [unix]

about:
  home: https://developers.google.com/protocol-buffers
  dev_url: https://github.com/protocolbuffers/protobuf
  doc_url: https://protobuf.dev/overview/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bazel rules for protobuf
  description: Bazel rules for protobuf

extra:
  recipe-maintainers:
    - conda-forge/libprotobuf
