context:
  version: "30.1"
  major: 5

package:
  name: protobuf-bazel-rules
  version: ${{ version }}

source:
  url: https://github.com/protocolbuffers/protobuf/releases/download/v${{ version }}/protobuf-${{ version }}.tar.gz
  sha256: 9df0e9e8ebe39f4fbbb9cf7db3d811287fe3616b2f191eb2bf5eaa12539c881f

build:
  number: 0
  noarch: generic

requirements:
  run_constraints:
    - protobuf ${{ major }}.${{ version }}.*
    - libprotobuf ${{ major }}.${{ version }}.*

tests:
  - package_contents:
      files:
        - share/bazel/protobuf/bazel/cc_proto_library.bzl

about:
  homepage: https://developers.google.com/protocol-buffers/
  repository: https://github.com/protocolbuffers/protobuf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bazel rules for protobuf

extra:
  recipe-maintainers:
    - conda-forge/libprotobuf
